# Generated by Django 5.0 on 2024-02-26 13:35

import Main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_cv_user_alter_cv_qualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalityquestion',
            name='tag',
            field=models.CharField(choices=[('EXT', 'EXT'), ('EST', 'EST'), ('AGR', 'AGR'), ('CSN', 'CSN'), ('OPN', 'OPN')], default='EXT', max_length=50, validators=[Main.models.PersonalityQuestion.validate_tag_count]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personalityattempt',
            name='answer',
            field=models.IntegerField(choices=[(1, 'Totally Disagree'), (2, 'Slightly Disagree'), (3, 'Neutral'), (4, 'Slightly Agree'), (5, 'Totally Agree')]),
        ),
    ]
