# Generated by Django 5.0.2 on 2024-02-29 21:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_result_unique_user_role_result'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='aptitudeattempt',
            name='unique_user_aptitude_question',
        ),
        migrations.RemoveConstraint(
            model_name='personalityattempt',
            name='unique_user_personality_question',
        ),
        migrations.AddConstraint(
            model_name='aptitudeattempt',
            constraint=models.UniqueConstraint(fields=('user', 'question', 'job'), name='unique_user_job_aptitude_question'),
        ),
        migrations.AddConstraint(
            model_name='personalityattempt',
            constraint=models.UniqueConstraint(fields=('user', 'question', 'job'), name='unique_user_job_personality_question'),
        ),
    ]
