# Generated by Django 5.0.2 on 2024-03-03 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_remove_aptitudeattempt_unique_user_aptitude_question_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='date_of_birth',
        ),
        migrations.AlterField(
            model_name='cv',
            name='previous_jobs',
            field=models.PositiveSmallIntegerField(verbose_name='Years of Experience'),
        ),
    ]
