# Generated by Django 5.0.2 on 2024-03-03 22:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0008_remove_cv_date_of_birth_alter_cv_previous_jobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2006, 3, 8, 23, 55, 6, 414439)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cv',
            name='previous_jobs',
            field=models.JSONField(max_length=1024, verbose_name='Years of Experience'),
        ),
    ]
